# Generated by Django 4.2 on 2023-04-14 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crewpay", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crewplanneruser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crewplanner_user",
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="StaffologyUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "staffology_key",
                    models.CharField(help_text="Required. Staffology API key", max_length=500, unique=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staffology_user",
                        to=settings.AUTH_USER_MODEL,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
