# Generated by Django 4.2 on 2023-04-14 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crewpay", "0002_alter_crewplanneruser_user_staffologyuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crewplanneruser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crewplanner_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="staffologyuser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="staffology_user", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
