# Generated by Django 4.2 on 2023-04-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crewpay", "0006_rename_employees_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="status",
            field=models.CharField(
                default="ACTIVE", help_text="Active or Inactive (CP driven)", max_length=20, unique=True
            ),
            preserve_default=False,
        ),
    ]
