# Generated by Django 4.2 on 2023-04-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crewpay", "0009_invalidemployee"),
    ]

    operations = [
        migrations.AddField(
            model_name="invalidemployee",
            name="name",
            field=models.CharField(default="name", max_length=100),
            preserve_default=False,
        ),
    ]
