# Generated by Django 4.2 on 2023-04-24 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crewpay", "0011_alter_invalidemployee_employer"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="pay_period",
            field=models.CharField(default="Monthly", max_length=20),
        ),
        migrations.AlterField(
            model_name="invalidemployee",
            name="employer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="invalid_employees", to="crewpay.employer"
            ),
        ),
    ]
