# Generated by Django 4.2 on 2023-04-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crewpay", "0013_invalidshift"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="payrollCode",
            field=models.CharField(default=1, help_text="Staffology payroll code", max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
