# Generated by Django 4.2.1 on 2023-06-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crewpay", "0017_employee_payload_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="payroll_code",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="staffology_id",
        ),
        migrations.AlterField(
            model_name="employer",
            name="id",
            field=models.CharField(
                help_text="shape employerId", max_length=500, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.DeleteModel(
            name="StaffologyUser",
        ),
    ]
