# Generated by Django 4.2.1 on 2023-07-11 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crewpay", "0018_remove_employee_payroll_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employer",
            name="pay_period",
        ),
    ]
