# Generated by Django 4.2 on 2023-04-17 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crewpay", "0005_employees"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Employees",
            new_name="Employee",
        ),
    ]
