# Generated by Django 4.2 on 2023-04-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crewpay", "0007_employee_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.CharField(help_text="ACTIVE or ARCHIVED (CP driven)", max_length=20),
        ),
    ]
