# Generated by Django 4.2 on 2023-04-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crewpay", "0008_alter_employee_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvalidEmployee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("employee_id", models.CharField(max_length=50)),
                ("error", models.TextField()),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                ("employer", models.CharField(max_length=50)),
            ],
        ),
    ]
