# Generated by Django 4.2 on 2023-04-26 11:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crewpay", "0014_employee_payrollcode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="payrollCode",
            new_name="payroll_code",
        ),
    ]
