# Generated by Django 4.2 on 2023-05-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crewpay", "0016_alter_employee_payroll_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="payload_hash",
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
